# Generated by Django 5.0.7 on 2024-07-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.CharField(choices=[('G', 'グー'), ('C', 'チョキ'), ('P', 'パー')], max_length=1)),
                ('computer_choice', models.CharField(choices=[('G', 'グー'), ('C', 'チョキ'), ('P', 'パー')], max_length=1)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
